imagePullPolicy: Always
nodeSelector: {}

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: multi-juicer.local
      paths:
        - "/"
  tls: []

service:
  type: ClusterIP
  port: 3000

balancer:
  cookie:
    secure: true
    name: balancer
    # Populate balancer.cookie.cookieParserSecret before deployment
    cookieParserSecret: null
  repository: iteratec/juice-balancer
  tag: null
  replicas: 1
  service:
    type: ClusterIP
    clusterIP: null
    loadBalancerIP: null
    loadBalancerSourceRanges: null
    externalIPs: null
  resources:
    requests:
      memory: 256Mi
      cpu: 400m
    limits:
      memory: 256Mi
      cpu: 400m
  securityContext: {}
  affinity: {}
  tolerations: []
  skipOwnerReference: false
  metrics:
    enabled: false
    dashboards:
      enabled: false
    serviceMonitor:
      enabled: false
    basicAuth:
      username: prometheus-scraper
      # Populate balancer.metrics.basicAuth.password before deployment
      password: null

juiceShop:
  # Configure juiceShop.maxInstances to number of participants
  maxInstances: 10
  image: bkimminich/juice-shop
  tag: latest
  # Populate juiceShop.ctfKey before deployment
  ctfKey: null
  # Specify a custom Juice Shop config.yaml. See: https://pwning.owasp-juice.shop/part1/customization.html#yaml-configuration-file
  config: |
    application:
      logo: JuiceShopCTF_Logo.png
      favicon: favicon_ctf.ico
      showVersionNumber: false
      showGitHubLinks: false
    challenges:
      showHints: true
      showCodeSnippets: solved
      safetyOverride: true
    hackingInstructor:
      isEnabled: true
    ctf:
      showFlagsInNotifications: false
  nodeEnv: "multi-juicer"
  resources:
    requests:
      cpu: 150m
      memory: 200Mi
  securityContext: {}
  env: []
  envFrom: []
  volumes: []
  volumeMounts: []

progressWatchdog:
  repository: iteratec/progress-watchdog
  tag: null
  resources:
    requests:
      memory: 48Mi
      cpu: 20m
    limits:
      memory: 48Mi
      cpu: 20m
  securityContext: {}

juiceShopCleanup:
  repository: iteratec/cleaner
  tag: null
  enabled: true
  # Configure juiceShopCleanup.gracePeriod to exceed length of event
  gracePeriod: 1d
  cron: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 256Mi
  securityContext: {}
  affinity: {}
  tolerations: []
